### ISSUE TITLE
Google翻訳結果の文字列の受け渡し

### ISSUE THREAD

**Issue by Natr0571** [itto4869/simultaneous-translation#1]
translate_google.jsで現在googleTranslatedTextに翻訳結果を代入していないので代入するように修正

**Comment by itto4869** [comment]
xmlhttprequestは非推奨らしいのでfetch apiに変更した．翻訳関数を非同期対応して翻訳結果を変数に入れられるようにした．
同じ要領でDeepLの翻訳も作って，ブラウザに表示するコードは分けたかったのでdisplay.jsを新たに作成してindex.htmlでインポートしている
